# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

source "https://rubygems.org"

gem 'fastlane', '~> 2.97.0'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)

gem 'danger-android_version_change', '~> 0.1.2'
gem "danger", "~> 5.6"

gem "overcommit", "~> 0.46.0"
