package com.levibostian.androidblanky.service.error.nonfatal

import com.levibostian.androidblanky.service.model.AppConstants

class NoInternetConnectionException : NonFatalAppError(AppConstants.httpNoInternetConnectionExceptionMessage)