# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.35.1"

default_platform :android

platform :android do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta_beta do
    foo = prompt(text: "Did you make sure to enter release notes in ./fastlane/beta_release_notes.txt? [y]")
    bar = prompt(text: "Did you increment the version in build.gradle? [y]")

    groups = ['internal-team']

    gradle(task: "assembleBetaRelease")
    crashlytics(api_token: 'apitoken',
             build_secret: 'buildsecret',
                 apk_path: './app/build/outputs/apk/app-beta-release.apk',
                   groups: groups,
               notes_path: './fastlane/beta_release_notes.txt',
            notifications: true)
    notification(subtitle: "Finished beta release", message: "Released new Beta build of app")
  end

  lane :app_icon do
    android_appicon(appicon_image_file: 'fastlane/metadata/icons/app_icon.png',
      appicon_devices: [:phone, :tablet],
      appicon_path: 'app/src/main/res/mipmap')
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    supply
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded. 
# Learn more at https://github.com/fastlane/fastlane#metrics
